### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by CFarzaneh** [Sinrel/AnjoCaido-Launcher#1]
English localization please

**Comment by GTRsdk** [comment]
It's possible to fork this and make an English version.
It doesn't look to be very easy to make it localized at the moment, and keep Russian in it.

**Comment by Sarkhad** [comment]
Now the development of this launcher is stopped.
Soon I completely rewrite this launcher with using Sinrel Launcher Engine (SLE) 2.0 
Todo:
- Support Minecraft after 1.6
- Support of localization ( all phrases will be in file, not in code! )
- Old code by AnjoCaido will be replaced (Design will not change)

If you want to know more please contact me on Skype. D_ART98

**Comment by CFarzaneh** [comment]
Sweet awesome! Let me know if you need help with anything.

**Comment by Sarkhad** [comment]
But i will be starting develop after 6-7th of August.

P.S You can find startup line for Minecraft 1.6+ in bat-script

**Comment by crunchbanger** [comment]
yeah english will be good. i know a bit of russian so i can help if you want. and then i can also translate it to polish.

**Comment by Sarkhad** [comment]
Soon I will start making new update, where I add the support of multilanguages. ( I cannot work, because I don't have notebook)
If you can, start translating it in English, please. When you finish it, just write in that look:
 Phrase in Russian - Phrase in English

**Comment by Akirus** [comment]
English Language is supported now
